{{- if .Values.relay.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-relay
  labels:
    app: {{ .Release.Name }}-relay
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.relay.service.type }}
  ports:
    - port: {{ .Values.relay.service.port }}
      targetPort: {{ .Values.relay.service.port }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-relay
{{- end }}