services:
  # Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: everpath
      POSTGRES_USER: everpath
      POSTGRES_PASSWORD: everpath123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/data/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U everpath -d everpath"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Object Storage
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: everpath
      MINIO_ROOT_PASSWORD: everpath123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # API Service
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://everpath:everpath123@postgres:5432/everpath
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=everpath
      - MINIO_SECRET_KEY=everpath123
      - JWT_SECRET=your-jwt-secret-change-in-production
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./services/api:/app

  # Web App
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-nextauth-secret-change-in-production
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./apps/web:/app
      - /app/node_modules

  # Admin App
  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=your-nextauth-secret-change-in-production
    ports:
      - "3001:3001"
    depends_on:
      - api
    volumes:
      - ./apps/admin:/app
      - /app/node_modules

  # Worker Service
  worker:
    build:
      context: ./services/worker
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://everpath:everpath123@postgres:5432/everpath
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./services/worker:/app

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  minio_data: