name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: atluxia_test
          POSTGRES_USER: atluxia
          POSTGRES_PASSWORD: atluxia123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9

    - name: Install dependencies
      run: pnpm install

    - name: Type check
      run: pnpm typecheck

    - name: Lint
      run: pnpm lint

    - name: Build
      run: pnpm build

    - name: Run tests
      run: pnpm test
      env:
        DATABASE_URL: postgresql://atluxia:atluxia123@localhost:5432/atluxia_test
        REDIS_URL: redis://localhost:6379
        NODE_ENV: test

  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    strategy:
      matrix:
        service:
          - nomad-web
          - polyverse-web
          - booking
          - drivers
          - immigration
          - vehicles
          - opengrid
          - truth-agent
          - truth-graph

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./apps/${{ matrix.service }}/Dockerfile
        push: false
        tags: atluxia/${{ matrix.service }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max